# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Heart' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Heart
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'FirebaseAnalytics'

  pod 'SWTableViewCell', '~> 0.3.7'

  # pod 'KASlideShow'
  pod 'SDWebImage', '~>3.8'
  
  # https://github.com/HeshamMegid/HMSegmentedControl
  # pod 'HMSegmentedControl'

  pod 'ZXingObjC', '~> 3.2.0'
end
