# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iChat

    # Pods for Heart
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'


  pod 'SWTableViewCell', '~> 0.3.7'

  # pod 'KASlideShow'
  pod 'SDWebImage', '~>3.8'

  pod 'JSQMessagesViewController'

  # https://github.com/scalessec/Toast
  # pod 'Toast', '~> 3.1.0'
end
